server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game_xxx
    username: root
    password: 14092001
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
api:
  prefix: api/v1

